import type { Payload, PayloadRequest } from 'payload'
import JSZip from 'jszip'

import { getServerSideURL } from '@/infra/utils/getURL'

import {
  BLOB_DIR,
  BUNDLE_MANIFEST_VERSION,
  MANIFEST_FILENAME,
  PROMOTED_COLLECTIONS,
  PromotedCollection,
} from './constants'
import type { BundleManifest, BundledDoc, BundledMedia, ExportReport } from './types'

interface MediaRecord {
  id: string
  type?: string
  filename?: string | null
  mimeType?: string | null
  url?: string | null
  [k: string]: unknown
}

interface ExportResult {
  zipBuffer: Buffer
  report: ExportReport
}

/**
 * Computed Payload-side fields that the import side must NOT carry across
 * environments. `createdAt`/`updatedAt` are regenerated by Mongoose, the
 * upload fields are regenerated when the binary is re-uploaded to the target
 * Vercel Blob store, and the legacy `_id` shadows Payload's `id`.
 */
const STRIPPED_FIELDS = new Set(['_id', 'createdAt', 'updatedAt', 'sizes', 'thumbnailURL'])

const STRIPPED_MEDIA_FIELDS = new Set([
  'filename',
  'mimeType',
  'filesize',
  'url',
  'width',
  'height',
])

function stripDoc(
  doc: Record<string, unknown>,
  collection: PromotedCollection,
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(doc)) {
    if (STRIPPED_FIELDS.has(key)) continue
    if (collection === 'media' && STRIPPED_MEDIA_FIELDS.has(key)) continue
    out[key] = value
  }
  return out
}

async function fetchAllDocs(
  payload: Payload,
  req: PayloadRequest,
  collection: PromotedCollection,
): Promise<Record<string, unknown>[]> {
  const docs: Record<string, unknown>[] = []
  let page = 1
  const pageSize = 200
  // Page through with depth: 0 so relationships stay as IDs, which is exactly
  // what the import side will write back. Loop until we exhaust totalPages so
  // collections larger than the page size are fully captured.
  for (;;) {
    const result = await payload.find({
      collection,
      depth: 0,
      limit: pageSize,
      page,
      overrideAccess: true,
      req,
    })
    docs.push(...(result.docs as unknown as Record<string, unknown>[]))
    if (page >= (result.totalPages ?? 1)) break
    page += 1
  }
  return docs
}

function getMediaBlobExtension(media: MediaRecord): string {
  const filename = media.filename
  if (typeof filename === 'string') {
    const dot = filename.lastIndexOf('.')
    if (dot > 0) return filename.slice(dot)
  }
  return ''
}

async function fetchMediaBinary(media: MediaRecord, baseUrl: string): Promise<Buffer | null> {
  if (!media.url) return null
  // External media (YouTube, Vimeo) have type='external' and no uploaded file —
  // the import side recreates the embed metadata from the record alone.
  if (media.type === 'external') return null

  const absolute = media.url.startsWith('http')
    ? media.url
    : `${baseUrl}${media.url.startsWith('/') ? '' : '/'}${media.url}`

  const response = await fetch(absolute)
  if (!response.ok) {
    throw new Error(`Failed to fetch media ${media.id} from ${absolute}: HTTP ${response.status}`)
  }
  const arrayBuffer = await response.arrayBuffer()
  return Buffer.from(arrayBuffer)
}

export async function exportContent(payload: Payload, req: PayloadRequest): Promise<ExportResult> {
  const startedAt = Date.now()
  const zip = new JSZip()
  const counts: Record<PromotedCollection, number> = {
    media: 0,
    courses: 0,
    chapters: 0,
    lessons: 0,
    exercises: 0,
  }
  const collections: BundleManifest['collections'] = {
    media: [],
    courses: [],
    chapters: [],
    lessons: [],
    exercises: [],
  }

  const baseUrl = getServerSideURL()
  let blobCount = 0
  let blobBytes = 0

  // 1. Media first — we capture the binaries alongside the records so the
  //    import side can re-upload to the target Vercel Blob store before
  //    creating any document that references them.
  //
  //    Records we can't bundle cleanly are dropped from the manifest entirely
  //    instead of going in with `blobEntry: null` — Payload's media
  //    `validateMediaUpload` hook rejects creates that have a non-external
  //    type and no file, so a bundle that included such records would always
  //    fail import. Any document later referencing a dropped media id ends
  //    up with a dangling ref on the target, which is logged but doesn't
  //    block the import.
  const mediaDocs = (await fetchAllDocs(payload, req, 'media')) as MediaRecord[]
  for (const media of mediaDocs) {
    const stripped = stripDoc(media as Record<string, unknown>, 'media')
    const isExternal = media.type === 'external'
    let blobEntry: string | null = null

    if (!isExternal) {
      try {
        const binary = await fetchMediaBinary(media, baseUrl)
        if (binary) {
          const ext = getMediaBlobExtension(media)
          blobEntry = `${BLOB_DIR}/${media.id}${ext}`
          zip.file(blobEntry, binary)
          blobCount += 1
          blobBytes += binary.length
        }
      } catch (error) {
        payload.logger.warn(
          { err: error, mediaId: media.id },
          '[content-promotion/export] Failed to fetch media binary; skipping record',
        )
      }
    }

    // Non-external media without a fetched binary can't be recreated on the
    // target — skip the record entirely rather than ship a record that will
    // fail validation on import.
    if (!isExternal && !blobEntry) {
      payload.logger.warn(
        { mediaId: media.id, mediaType: media.type ?? 'unknown' },
        '[content-promotion/export] Non-external media has no fetchable binary; omitting from bundle',
      )
      continue
    }

    const bundled: BundledMedia = {
      ...(stripped as Record<string, unknown>),
      id: String(media.id),
      blobEntry,
    } as BundledMedia
    collections.media.push(bundled)
  }
  counts.media = collections.media.length

  // 2. Pure record collections — capture in dependency order so the manifest
  //    reads top-to-bottom in the same order the import side creates them.
  for (const collection of PROMOTED_COLLECTIONS) {
    if (collection === 'media') continue
    const docs = await fetchAllDocs(payload, req, collection)
    for (const doc of docs) {
      const stripped = stripDoc(doc, collection)
      collections[collection].push({
        ...stripped,
        id: String((doc as { id: unknown }).id),
      } as BundledDoc)
    }
    counts[collection] = collections[collection].length
  }

  const manifest: BundleManifest = {
    version: BUNDLE_MANIFEST_VERSION,
    exportedAt: new Date().toISOString(),
    source: {
      serverUrl: baseUrl,
    },
    counts,
    collections,
  }

  zip.file(MANIFEST_FILENAME, JSON.stringify(manifest, null, 2))

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })

  return {
    zipBuffer,
    report: {
      counts,
      blobs: blobCount,
      bytes: blobBytes,
      durationMs: Date.now() - startedAt,
    },
  }
}
