import type { Payload, PayloadRequest } from 'payload'
import JSZip from 'jszip'

import { getServerSideURL } from '@/infra/utils/getURL'

import {
  BLOB_DIR,
  BUNDLE_MANIFEST_VERSION,
  MANIFEST_FILENAME,
  PROMOTED_COLLECTIONS,
  PromotedCollection,
} from './constants'
import type { BundleManifest, BundledDoc, BundledMedia, ExportReport } from './types'

interface MediaRecord {
  id: string
  type?: string
  filename?: string | null
  mimeType?: string | null
  url?: string | null
  [k: string]: unknown
}

interface ExportResult {
  zipBuffer: Buffer
  report: ExportReport
}

export interface ExportContentOptions {
  /**
   * Course IDs to include in the bundle. Chapters/lessons/exercises are
   * walked transitively from these courses, plus any media referenced by
   * the walked docs. Must contain at least one ID.
   */
  courseIds: string[]
}

/**
 * Computed Payload-side fields that the import side must NOT carry across
 * environments. `createdAt`/`updatedAt` are regenerated by Mongoose, the
 * upload fields are regenerated when the binary is re-uploaded to the target
 * Vercel Blob store, and the legacy `_id` shadows Payload's `id`.
 */
const STRIPPED_FIELDS = new Set(['_id', 'createdAt', 'updatedAt', 'sizes', 'thumbnailURL'])

const STRIPPED_MEDIA_FIELDS = new Set([
  'filename',
  'mimeType',
  'filesize',
  'url',
  'width',
  'height',
])

function stripDoc(
  doc: Record<string, unknown>,
  collection: PromotedCollection,
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(doc)) {
    if (STRIPPED_FIELDS.has(key)) continue
    if (collection === 'media' && STRIPPED_MEDIA_FIELDS.has(key)) continue
    out[key] = value
  }
  return out
}

async function fetchDocsByFilter(
  payload: Payload,
  req: PayloadRequest,
  collection: PromotedCollection,
  whereIds: { field: string; ids: string[] },
): Promise<Record<string, unknown>[]> {
  if (whereIds.ids.length === 0) return []
  const docs: Record<string, unknown>[] = []
  let page = 1
  const pageSize = 200
  // Page through with depth: 0 so relationships stay as IDs, which is exactly
  // what the import side will write back. Loop until we exhaust totalPages so
  // collections larger than the page size are fully captured.
  for (;;) {
    const result = await payload.find({
      collection,
      where: { [whereIds.field]: { in: whereIds.ids } },
      depth: 0,
      limit: pageSize,
      page,
      overrideAccess: true,
      req,
    })
    docs.push(...(result.docs as unknown as Record<string, unknown>[]))
    if (page >= (result.totalPages ?? 1)) break
    page += 1
  }
  return docs
}

function getMediaBlobExtension(media: MediaRecord): string {
  const filename = media.filename
  if (typeof filename === 'string') {
    const dot = filename.lastIndexOf('.')
    if (dot > 0) return filename.slice(dot)
  }
  return ''
}

async function fetchMediaBinary(media: MediaRecord, baseUrl: string): Promise<Buffer | null> {
  if (!media.url) return null
  // External media (YouTube, Vimeo) have type='external' and no uploaded file —
  // the import side recreates the embed metadata from the record alone.
  if (media.type === 'external') return null

  const absolute = media.url.startsWith('http')
    ? media.url
    : `${baseUrl}${media.url.startsWith('/') ? '' : '/'}${media.url}`

  const response = await fetch(absolute)
  if (!response.ok) {
    throw new Error(`Failed to fetch media ${media.id} from ${absolute}: HTTP ${response.status}`)
  }
  const arrayBuffer = await response.arrayBuffer()
  return Buffer.from(arrayBuffer)
}

/**
 * Collects the media IDs reachable from a single document. Explicitly
 * enumerates the known upload-field paths per collection so we don't pick up
 * spurious 24-hex strings (option IDs, block IDs, etc.) that happen to share
 * the ObjectId shape.
 *
 * For exercises, the `content` JSON tree carries `mediaIds` arrays inside
 * rich-text blocks and inside MCQ option contents — walked recursively below.
 */
function collectMediaIdsFromDoc(
  doc: Record<string, unknown>,
  collection: PromotedCollection,
  out: Set<string>,
): void {
  const pushId = (value: unknown) => {
    if (typeof value === 'string' && value.length > 0) out.add(value)
  }
  const pushArr = (value: unknown) => {
    if (Array.isArray(value)) value.forEach(pushId)
  }

  if (collection === 'courses') {
    pushArr(doc.mediaFiles)
  } else if (collection === 'chapters') {
    pushArr(doc.mediaFiles)
  } else if (collection === 'lessons') {
    pushArr(doc.contentFiles)
  } else if (collection === 'exercises') {
    pushId(doc.sourceDoc)
    const content = doc.content as Record<string, unknown> | undefined
    const blocks = (content?.blocks as unknown[]) ?? []
    for (const block of blocks) {
      if (!block || typeof block !== 'object') continue
      const b = block as Record<string, unknown>
      pushArr(b.mediaIds)
      // MCQ-style blocks: each option has its own rich_text content with mediaIds.
      const options = b.options as unknown[] | undefined
      if (Array.isArray(options)) {
        for (const opt of options) {
          if (!opt || typeof opt !== 'object') continue
          const optContent = (opt as Record<string, unknown>).content as
            | Record<string, unknown>
            | undefined
          if (optContent) pushArr(optContent.mediaIds)
        }
      }
    }
  }
}

export async function exportContent(
  payload: Payload,
  req: PayloadRequest,
  options: ExportContentOptions,
): Promise<ExportResult> {
  if (!options.courseIds || options.courseIds.length === 0) {
    throw new Error('exportContent requires at least one courseId')
  }
  // De-dupe to be safe against duplicate IDs from query parsing.
  const courseIds = Array.from(new Set(options.courseIds))

  const startedAt = Date.now()
  const zip = new JSZip()
  const counts: Record<PromotedCollection, number> = {
    media: 0,
    courses: 0,
    chapters: 0,
    lessons: 0,
    exercises: 0,
  }
  const collections: BundleManifest['collections'] = {
    media: [],
    courses: [],
    chapters: [],
    lessons: [],
    exercises: [],
  }

  // 1. Pull the scoped tree. Lessons and exercises both carry a denormalized
  //    `course` field (populated by their respective beforeChange hooks) so we
  //    can filter them by `course in [...]` directly, avoiding a chapter-join
  //    intermediate hop.
  const courseDocs = await fetchDocsByFilter(payload, req, 'courses', {
    field: 'id',
    ids: courseIds,
  })
  const chapterDocs = await fetchDocsByFilter(payload, req, 'chapters', {
    field: 'course',
    ids: courseIds,
  })
  const lessonDocs = await fetchDocsByFilter(payload, req, 'lessons', {
    field: 'course',
    ids: courseIds,
  })
  const exerciseDocs = await fetchDocsByFilter(payload, req, 'exercises', {
    field: 'course',
    ids: courseIds,
  })

  // 2. Walk for media IDs referenced by any of the scoped docs.
  const referencedMediaIds = new Set<string>()
  for (const doc of courseDocs) collectMediaIdsFromDoc(doc, 'courses', referencedMediaIds)
  for (const doc of chapterDocs) collectMediaIdsFromDoc(doc, 'chapters', referencedMediaIds)
  for (const doc of lessonDocs) collectMediaIdsFromDoc(doc, 'lessons', referencedMediaIds)
  for (const doc of exerciseDocs) collectMediaIdsFromDoc(doc, 'exercises', referencedMediaIds)

  // 3. Fetch only the media records actually referenced by the scoped tree.
  const mediaDocs = (
    referencedMediaIds.size > 0
      ? await fetchDocsByFilter(payload, req, 'media', {
          field: 'id',
          ids: Array.from(referencedMediaIds),
        })
      : []
  ) as MediaRecord[]

  const baseUrl = getServerSideURL()
  let blobCount = 0
  let blobBytes = 0

  // 4. Media first in the bundle — the import side re-uploads to the target
  //    Vercel Blob store before creating any document that references them.
  //    Records we can't bundle cleanly are dropped from the manifest entirely
  //    instead of going in with `blobEntry: null` — Payload's media
  //    `validateMediaUpload` hook rejects creates that have a non-external
  //    type and no file, so a bundle that included such records would always
  //    fail import. Any document later referencing a dropped media id ends
  //    up with a dangling ref on the target, which is logged but doesn't
  //    block the import.
  for (const media of mediaDocs) {
    const stripped = stripDoc(media as Record<string, unknown>, 'media')
    const isExternal = media.type === 'external'
    let blobEntry: string | null = null

    if (!isExternal) {
      try {
        const binary = await fetchMediaBinary(media, baseUrl)
        if (binary) {
          const ext = getMediaBlobExtension(media)
          blobEntry = `${BLOB_DIR}/${media.id}${ext}`
          zip.file(blobEntry, binary)
          blobCount += 1
          blobBytes += binary.length
        }
      } catch (error) {
        payload.logger.warn(
          { err: error, mediaId: media.id },
          '[content-promotion/export] Failed to fetch media binary; skipping record',
        )
      }
    }

    // Non-external media without a fetched binary can't be recreated on the
    // target — skip the record entirely rather than ship a record that will
    // fail validation on import.
    if (!isExternal && !blobEntry) {
      payload.logger.warn(
        { mediaId: media.id, mediaType: media.type ?? 'unknown' },
        '[content-promotion/export] Non-external media has no fetchable binary; omitting from bundle',
      )
      continue
    }

    const bundled: BundledMedia = {
      ...(stripped as Record<string, unknown>),
      id: String(media.id),
      blobEntry,
    } as BundledMedia
    collections.media.push(bundled)
  }
  counts.media = collections.media.length

  // 5. Push the scoped tree records into the manifest in dependency order.
  const treeByCollection: Record<
    Exclude<PromotedCollection, 'media'>,
    Record<string, unknown>[]
  > = {
    courses: courseDocs,
    chapters: chapterDocs,
    lessons: lessonDocs,
    exercises: exerciseDocs,
  }
  for (const collection of PROMOTED_COLLECTIONS) {
    if (collection === 'media') continue
    for (const doc of treeByCollection[collection]) {
      const stripped = stripDoc(doc, collection)
      collections[collection].push({
        ...stripped,
        id: String((doc as { id: unknown }).id),
      } as BundledDoc)
    }
    counts[collection] = collections[collection].length
  }

  const manifest: BundleManifest = {
    version: BUNDLE_MANIFEST_VERSION,
    exportedAt: new Date().toISOString(),
    source: {
      serverUrl: baseUrl,
    },
    counts,
    collections,
  }

  zip.file(MANIFEST_FILENAME, JSON.stringify(manifest, null, 2))

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })

  return {
    zipBuffer,
    report: {
      counts,
      blobs: blobCount,
      bytes: blobBytes,
      durationMs: Date.now() - startedAt,
    },
  }
}

// Exported only for the unit tests; not part of the public service surface.
export const __test = { collectMediaIdsFromDoc }
