import type { Payload, PayloadRequest } from 'payload'
import JSZip from 'jszip'

import { getServerSideURL } from '@/infra/utils/getURL'

import {
  BLOB_DIR,
  BUNDLE_MANIFEST_VERSION,
  MANIFEST_FILENAME,
  PROMOTED_COLLECTIONS,
  PromotedCollection,
} from './constants'
import type { BundleManifest, BundledDoc, BundledMedia, ExportReport } from './types'

interface MediaRecord {
  id: string
  type?: string
  filename?: string | null
  mimeType?: string | null
  url?: string | null
  [k: string]: unknown
}

interface ExportResult {
  zipBuffer: Buffer
  report: ExportReport
}

export interface ExportContentOptions {
  /**
   * Course IDs to include in the bundle. Chapters/lessons/exercises are
   * walked transitively from these courses, plus any media referenced by
   * the walked docs. Must contain at least one ID.
   */
  courseIds: string[]
}

/**
 * Computed Payload-side fields that the import side must NOT carry across
 * environments. `createdAt`/`updatedAt` are regenerated by Mongoose, the
 * upload fields are regenerated when the binary is re-uploaded to the target
 * Vercel Blob store, and the legacy `_id` shadows Payload's `id`.
 */
const STRIPPED_FIELDS = new Set(['_id', 'createdAt', 'updatedAt', 'sizes', 'thumbnailURL'])

// `filename` and `mimeType` are KEPT in the bundle because the import side
// passes them to `payload.create({ file: { name, mimetype } })` — without
// them the upload falls back to `<id>.bin` + `application/octet-stream`,
// which makes Vercel Blob store the file under a `.bin` extension and the
// admin UI render it as a generic blob instead of an image/pdf/video.
// `url`/`filesize`/`width`/`height` ARE stripped — they're recomputed by
// the Vercel Blob plugin from the freshly-uploaded file on the target.
const STRIPPED_MEDIA_FIELDS = new Set(['url', 'filesize', 'width', 'height'])

/**
 * Extracts every `exerciseRef.exercise` id from the `blocks` playlist of
 * each lesson. `blocks` is stored as a `textarea` (JSON-serialized string
 * — see Lessons.ts field config), so we parse each lesson individually and
 * ignore ones whose blocks are missing or malformed rather than aborting
 * the whole export.
 *
 * Exported so the pure JSON-string walk is unit-testable without a live
 * Payload.
 */
export function collectExerciseRefsFromLessonBlocks(
  lessons: Record<string, unknown>[],
): Set<string> {
  return collectRefsFromBlocksPlaylist(lessons, 'exerciseRef', 'exercise')
}

/**
 * Mirror of `collectExerciseRefsFromLessonBlocks` for the exercise-side
 * playlist: `exercise.blocks` is a JSON-string textarea listing every
 * child section as `{ blockType: 'sectionRef', section: '<id>' }`. Same
 * "playlist is the source of truth" rationale — the aggregator hook on
 * exercises reads this list to concatenate section content, so any section
 * the playlist references must be in the bundle even if `section.exercise`
 * points elsewhere (source-side drift).
 */
export function collectSectionRefsFromExerciseBlocks(
  exercises: Record<string, unknown>[],
): Set<string> {
  return collectRefsFromBlocksPlaylist(exercises, 'sectionRef', 'section')
}

function collectRefsFromBlocksPlaylist<K extends string>(
  parents: Record<string, unknown>[],
  wantedBlockType: string,
  refField: K,
): Set<string> {
  const ids = new Set<string>()
  for (const parent of parents) {
    const raw = parent.blocks
    if (typeof raw !== 'string' || raw.length === 0) continue
    let parsed: unknown
    try {
      parsed = JSON.parse(raw)
    } catch {
      continue
    }
    if (!Array.isArray(parsed)) continue
    for (const block of parsed) {
      if (!block || typeof block !== 'object') continue
      const b = block as Record<string, unknown>
      if (b.blockType !== wantedBlockType) continue
      const ref = b[refField]
      if (typeof ref === 'string' && ref.length > 0) ids.add(ref)
    }
  }
  return ids
}

function stripDoc(
  doc: Record<string, unknown>,
  collection: PromotedCollection,
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(doc)) {
    if (STRIPPED_FIELDS.has(key)) continue
    if (collection === 'media' && STRIPPED_MEDIA_FIELDS.has(key)) continue
    out[key] = value
  }
  return out
}

async function fetchDocsByFilter(
  payload: Payload,
  req: PayloadRequest,
  collection: PromotedCollection,
  whereIds: { field: string; ids: string[] },
): Promise<Record<string, unknown>[]> {
  if (whereIds.ids.length === 0) return []
  const docs: Record<string, unknown>[] = []
  let page = 1
  const pageSize = 200
  // Page through with depth: 0 so relationships stay as IDs, which is exactly
  // what the import side will write back. Loop until we exhaust totalPages so
  // collections larger than the page size are fully captured.
  for (;;) {
    const result = await payload.find({
      collection,
      where: { [whereIds.field]: { in: whereIds.ids } },
      depth: 0,
      limit: pageSize,
      page,
      overrideAccess: true,
      req,
    })
    docs.push(...(result.docs as unknown as Record<string, unknown>[]))
    if (page >= (result.totalPages ?? 1)) break
    page += 1
  }
  return docs
}

function getMediaBlobExtension(media: MediaRecord): string {
  const filename = media.filename
  if (typeof filename === 'string') {
    const dot = filename.lastIndexOf('.')
    if (dot > 0) return filename.slice(dot)
  }
  return ''
}

async function fetchMediaBinary(media: MediaRecord, baseUrl: string): Promise<Buffer | null> {
  if (!media.url) return null
  // External media (YouTube, Vimeo) have type='external' and no uploaded file —
  // the import side recreates the embed metadata from the record alone.
  if (media.type === 'external') return null

  const absolute = media.url.startsWith('http')
    ? media.url
    : `${baseUrl}${media.url.startsWith('/') ? '' : '/'}${media.url}`

  const response = await fetch(absolute)
  if (!response.ok) {
    throw new Error(`Failed to fetch media ${media.id} from ${absolute}: HTTP ${response.status}`)
  }
  const arrayBuffer = await response.arrayBuffer()
  return Buffer.from(arrayBuffer)
}

/**
 * Collects the media IDs reachable from a single document. Explicitly
 * enumerates the known upload-field paths per collection so we don't pick up
 * spurious 24-hex strings (option IDs, block IDs, etc.) that happen to share
 * the ObjectId shape.
 *
 * For exercises, the `content` JSON tree carries `mediaIds` arrays inside
 * rich-text blocks and inside MCQ option contents — walked recursively below.
 */
function collectMediaIdsFromDoc(
  doc: Record<string, unknown>,
  collection: PromotedCollection,
  out: Set<string>,
): void {
  const pushId = (value: unknown) => {
    if (typeof value === 'string' && value.length > 0) out.add(value)
  }
  const pushArr = (value: unknown) => {
    if (Array.isArray(value)) value.forEach(pushId)
  }

  if (collection === 'courses') {
    pushArr(doc.mediaFiles)
  } else if (collection === 'chapters') {
    pushArr(doc.mediaFiles)
  } else if (collection === 'lessons') {
    pushArr(doc.contentFiles)
  } else if (collection === 'exercises' || collection === 'sections') {
    // Sections use the same ContentSchema as exercises (see
    // sectionhandoff.md), so `content.blocks` has the same
    // rich-text/MCQ shape with the same `mediaIds`/`options[].content`
    // paths — one walk covers both.
    if (collection === 'exercises') pushId(doc.sourceDoc)
    const content = doc.content as Record<string, unknown> | undefined
    const blocks = (content?.blocks as unknown[]) ?? []
    for (const block of blocks) {
      if (!block || typeof block !== 'object') continue
      const b = block as Record<string, unknown>
      pushArr(b.mediaIds)
      // MCQ-style blocks: each option has its own rich_text content with mediaIds.
      const options = b.options as unknown[] | undefined
      if (Array.isArray(options)) {
        for (const opt of options) {
          if (!opt || typeof opt !== 'object') continue
          const optContent = (opt as Record<string, unknown>).content as
            | Record<string, unknown>
            | undefined
          if (optContent) pushArr(optContent.mediaIds)
        }
      }
    }
  }
}

export async function exportContent(
  payload: Payload,
  req: PayloadRequest,
  options: ExportContentOptions,
): Promise<ExportResult> {
  if (!options.courseIds || options.courseIds.length === 0) {
    throw new Error('exportContent requires at least one courseId')
  }
  // De-dupe to be safe against duplicate IDs from query parsing.
  const courseIds = Array.from(new Set(options.courseIds))

  const startedAt = Date.now()
  const zip = new JSZip()
  const counts: Record<PromotedCollection, number> = {
    media: 0,
    courses: 0,
    chapters: 0,
    lessons: 0,
    exercises: 0,
    sections: 0,
  }
  const collections: BundleManifest['collections'] = {
    media: [],
    courses: [],
    chapters: [],
    lessons: [],
    exercises: [],
    sections: [],
  }

  // 1. Pull the scoped tree by walking the required parent refs. We used to
  //    filter lessons and exercises directly on their denormalized `course`
  //    field, but that field is populated by a `beforeChange` hook wrapped in
  //    a try/catch — if the lookup ever silently failed (or the doc pre-dates
  //    the hook), the field stays empty and the whole doc drops out of the
  //    export. Walking chapter → lesson → exercise uses only fields Payload
  //    marks required (chapter.course, lesson.chapter, exercise.lesson) which
  //    can't be null in a valid doc, so no doc is silently omitted.
  const courseDocs = await fetchDocsByFilter(payload, req, 'courses', {
    field: 'id',
    ids: courseIds,
  })
  const chapterDocs = await fetchDocsByFilter(payload, req, 'chapters', {
    field: 'course',
    ids: courseIds,
  })
  const chapterIds = chapterDocs
    .map((c) => (c as { id?: unknown }).id)
    .filter((id): id is string => typeof id === 'string')
  const lessonDocs = await fetchDocsByFilter(payload, req, 'lessons', {
    field: 'chapter',
    ids: chapterIds,
  })
  const lessonIds = lessonDocs
    .map((l) => (l as { id?: unknown }).id)
    .filter((id): id is string => typeof id === 'string')
  const exerciseDocsByParent = await fetchDocsByFilter(payload, req, 'exercises', {
    field: 'lesson',
    ids: lessonIds,
  })

  // 1b. Union in any exercises referenced by lesson.blocks playlists but not
  //     picked up by the `exercise.lesson in [...]` filter above. The
  //     playlist is what the web renders from, so it is the effective
  //     source of truth for "which exercises belong to this lesson." When
  //     an exercise's `lesson` field storage-shape drifts from the parent
  //     query's expectations (real case: prod exercises 69eb1b87…f545/547/
  //     549 pointed at the correct lesson but the `in` filter dropped them,
  //     producing a bundle that rendered 60 on the target while prod
  //     rendered 63), the playlist union catches them.
  const playlistExerciseIds = collectExerciseRefsFromLessonBlocks(lessonDocs)
  const alreadyPulled = new Set(
    exerciseDocsByParent
      .map((d) => (d as { id?: unknown }).id)
      .filter((id): id is string => typeof id === 'string'),
  )
  const missingPlaylistIds = [...playlistExerciseIds].filter((id) => !alreadyPulled.has(id))
  const exerciseDocsFromPlaylist =
    missingPlaylistIds.length > 0
      ? await fetchDocsByFilter(payload, req, 'exercises', {
          field: 'id',
          ids: missingPlaylistIds,
        })
      : []
  if (exerciseDocsFromPlaylist.length > 0) {
    payload.logger.info(
      {
        recoveredFromPlaylist: exerciseDocsFromPlaylist.length,
        missingButNotFound: missingPlaylistIds.length - exerciseDocsFromPlaylist.length,
      },
      '[content-promotion/export] Recovered exercises referenced by lesson.blocks that the exercise.lesson filter missed',
    )
  }
  const exerciseDocs = [...exerciseDocsByParent, ...exerciseDocsFromPlaylist]

  // 1c. Pull sections for every scoped exercise, then union in any sections
  //     referenced by exercise.blocks playlists but missed by
  //     `section.exercise in [...]` (same "playlist is the source of truth"
  //     rationale as the exercise-side union above). Sections were added as
  //     a new layer between exercises and question content (see
  //     sectionhandoff.md); the aggregator hook on Exercises reads
  //     `exercise.blocks` to concatenate section content at read time, so
  //     the playlist governs what actually renders.
  const exerciseIds = exerciseDocs
    .map((e) => (e as { id?: unknown }).id)
    .filter((id): id is string => typeof id === 'string')
  const sectionDocsByParent =
    exerciseIds.length > 0
      ? await fetchDocsByFilter(payload, req, 'sections', {
          field: 'exercise',
          ids: exerciseIds,
        })
      : []
  const playlistSectionIds = collectSectionRefsFromExerciseBlocks(exerciseDocs)
  const alreadyPulledSections = new Set(
    sectionDocsByParent
      .map((d) => (d as { id?: unknown }).id)
      .filter((id): id is string => typeof id === 'string'),
  )
  const missingSectionIds = [...playlistSectionIds].filter((id) => !alreadyPulledSections.has(id))
  const sectionDocsFromPlaylist =
    missingSectionIds.length > 0
      ? await fetchDocsByFilter(payload, req, 'sections', {
          field: 'id',
          ids: missingSectionIds,
        })
      : []
  if (sectionDocsFromPlaylist.length > 0) {
    payload.logger.info(
      {
        recoveredFromPlaylist: sectionDocsFromPlaylist.length,
        missingButNotFound: missingSectionIds.length - sectionDocsFromPlaylist.length,
      },
      '[content-promotion/export] Recovered sections referenced by exercise.blocks that the section.exercise filter missed',
    )
  }
  const sectionDocs = [...sectionDocsByParent, ...sectionDocsFromPlaylist]

  // 2. Walk for media IDs referenced by any of the scoped docs.
  const referencedMediaIds = new Set<string>()
  for (const doc of courseDocs) collectMediaIdsFromDoc(doc, 'courses', referencedMediaIds)
  for (const doc of chapterDocs) collectMediaIdsFromDoc(doc, 'chapters', referencedMediaIds)
  for (const doc of lessonDocs) collectMediaIdsFromDoc(doc, 'lessons', referencedMediaIds)
  for (const doc of exerciseDocs) collectMediaIdsFromDoc(doc, 'exercises', referencedMediaIds)
  for (const doc of sectionDocs) collectMediaIdsFromDoc(doc, 'sections', referencedMediaIds)

  // 3. Fetch only the media records actually referenced by the scoped tree.
  const mediaDocs = (
    referencedMediaIds.size > 0
      ? await fetchDocsByFilter(payload, req, 'media', {
          field: 'id',
          ids: Array.from(referencedMediaIds),
        })
      : []
  ) as MediaRecord[]

  const baseUrl = getServerSideURL()
  let blobCount = 0
  let blobBytes = 0

  // 4. Media first in the bundle — the import side re-uploads to the target
  //    Vercel Blob store before creating any document that references them.
  //    Records we can't bundle cleanly are dropped from the manifest entirely
  //    instead of going in with `blobEntry: null` — Payload's media
  //    `validateMediaUpload` hook rejects creates that have a non-external
  //    type and no file, so a bundle that included such records would always
  //    fail import. Any document later referencing a dropped media id ends
  //    up with a dangling ref on the target, which is logged but doesn't
  //    block the import.
  for (const media of mediaDocs) {
    const stripped = stripDoc(media as Record<string, unknown>, 'media')
    const isExternal = media.type === 'external'
    let blobEntry: string | null = null

    if (!isExternal) {
      try {
        const binary = await fetchMediaBinary(media, baseUrl)
        if (binary) {
          const ext = getMediaBlobExtension(media)
          blobEntry = `${BLOB_DIR}/${media.id}${ext}`
          zip.file(blobEntry, binary)
          blobCount += 1
          blobBytes += binary.length
        }
      } catch (error) {
        payload.logger.warn(
          { err: error, mediaId: media.id },
          '[content-promotion/export] Failed to fetch media binary; skipping record',
        )
      }
    }

    // Non-external media without a fetched binary can't be recreated on the
    // target — skip the record entirely rather than ship a record that will
    // fail validation on import.
    if (!isExternal && !blobEntry) {
      payload.logger.warn(
        { mediaId: media.id, mediaType: media.type ?? 'unknown' },
        '[content-promotion/export] Non-external media has no fetchable binary; omitting from bundle',
      )
      continue
    }

    const bundled: BundledMedia = {
      ...(stripped as Record<string, unknown>),
      id: String(media.id),
      blobEntry,
    } as BundledMedia
    collections.media.push(bundled)
  }
  counts.media = collections.media.length

  // 5. Push the scoped tree records into the manifest in dependency order.
  const treeByCollection: Record<
    Exclude<PromotedCollection, 'media'>,
    Record<string, unknown>[]
  > = {
    courses: courseDocs,
    chapters: chapterDocs,
    lessons: lessonDocs,
    exercises: exerciseDocs,
    sections: sectionDocs,
  }
  for (const collection of PROMOTED_COLLECTIONS) {
    if (collection === 'media') continue
    for (const doc of treeByCollection[collection]) {
      const stripped = stripDoc(doc, collection)
      collections[collection].push({
        ...stripped,
        id: String((doc as { id: unknown }).id),
      } as BundledDoc)
    }
    counts[collection] = collections[collection].length
  }

  const manifest: BundleManifest = {
    version: BUNDLE_MANIFEST_VERSION,
    exportedAt: new Date().toISOString(),
    source: {
      serverUrl: baseUrl,
    },
    counts,
    collections,
  }

  zip.file(MANIFEST_FILENAME, JSON.stringify(manifest, null, 2))

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })

  return {
    zipBuffer,
    report: {
      counts,
      blobs: blobCount,
      bytes: blobBytes,
      durationMs: Date.now() - startedAt,
    },
  }
}

// Exported only for the unit tests; not part of the public service surface.
export const __test = { collectMediaIdsFromDoc }
