/**
 * PR creation for Nightly Docs Agent
 *
 * Creates or updates PRs with documentation changes.
 */

import { execSync } from 'node:child_process'
import type { Config } from './config-parser'
import type { ValidatedChange } from './patches'
import type { PatchResult } from './patches'

// ============================================================================
// Git/GitHub Commands
// ============================================================================

function exec(cmd: string): string {
  try {
    return execSync(cmd, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }).trim()
  } catch (err: unknown) {
    const error = err as { stderr?: string; message?: string }
    throw new Error(`Command failed: ${cmd}\n${error.stderr || error.message}`)
  }
}

function execSafe(cmd: string): { ok: boolean; output: string } {
  try {
    const output = execSync(cmd, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }).trim()
    return { ok: true, output }
  } catch (err: unknown) {
    const error = err as { stderr?: string; message?: string }
    return { ok: false, output: error.stderr || error.message || 'Unknown error' }
  }
}

// ============================================================================
// PR Operations
// ============================================================================

/**
 * Check if there's an open PR for the branch
 */
export function hasOpenPR(branch: string): boolean {
  const result = execSafe(`gh pr list --head ${branch} --state open --json number`)
  if (!result.ok) return false

  try {
    const prs = JSON.parse(result.output)
    return prs.length > 0
  } catch {
    return false
  }
}

/**
 * Get the PR number for an open PR
 */
function getOpenPRNumber(branch: string): number | null {
  const result = execSafe(`gh pr list --head ${branch} --state open --json number`)
  if (!result.ok) return null

  try {
    const prs = JSON.parse(result.output)
    return prs.length > 0 ? prs[0].number : null
  } catch {
    return null
  }
}

/**
 * Generate PR body
 */
function generatePRBody(
  results: PatchResult[],
  changes: ValidatedChange[],
  _config: Config,
): string {
  const timestamp = new Date().toISOString()

  // Collect unique triggering files
  const triggers = [...new Set(changes.flatMap((c) => c.actions.map((a) => a.trigger.path)))]

  // Generate trigger list
  const triggerList = triggers.map((t) => `- \`${t}\``).join('\n')

  // Generate change list
  const changeList = results
    .filter((r) => r.changed)
    .map((r) => `- \`${r.doc}\` → section: "${r.section}"`)
    .join('\n')

  // Generate evidence list
  const evidenceList = changes
    .flatMap((c) => c.combinedEvidence)
    .map((e) => `- ${e}`)
    .join('\n')

  // Use template or default
  const body = `## Nightly Docs Update

**Generated**: ${timestamp}
**Trigger**: Structural changes detected since last run

### Triggering Files
${triggerList}

### Documentation Changes
${changeList}

### Evidence
${evidenceList}

---
*This PR was automatically generated by the Nightly Docs Agent.*
*To tune rules, edit \`docs/nightly-docs-agent/CONFIG.md\`.*`

  return body
}

/**
 * Create a new PR
 */
export function createPR(
  results: PatchResult[],
  changes: ValidatedChange[],
  config: Config,
): string {
  const branch = config.prConfig.branch
  const base = config.prConfig.base
  const changedCount = results.filter((r) => r.changed).length
  const title = config.prConfig.titleTemplate.replace('{doc_count}', String(changedCount))
  const labels = config.prConfig.labels.join(',')

  // Check if branch already exists
  const branchExists = execSafe(`git rev-parse --verify ${branch}`).ok

  if (branchExists) {
    // Switch to existing branch
    exec(`git checkout ${branch}`)
    exec(`git pull origin ${branch} --rebase`)
  } else {
    // Create new branch
    exec(`git checkout -b ${branch}`)
  }

  // Stage and commit changes
  const changedDocs = results.filter((r) => r.changed).map((r) => r.doc)
  if (changedDocs.length === 0) {
    throw new Error('No files to commit')
  }

  for (const doc of changedDocs) {
    exec(`git add "${doc}"`)
  }

  const commitMessage = `docs(nightly): update documentation for structural changes

Co-Authored-By: Nightly Docs Agent <noreply@example.com>`

  exec(`git commit -m "${commitMessage}"`)

  // Push branch
  exec(`git push -u origin ${branch} --force-with-lease`)

  // Generate PR body
  const body = generatePRBody(results, changes, config)

  // Create PR
  const prResult = exec(
    `gh pr create --base ${base} --head ${branch} --title "${title}" --body "${body.replace(/"/g, '\\"')}" --label "${labels}"`,
  )

  // Return PR URL (gh pr create outputs the URL)
  return prResult
}

/**
 * Update an existing PR
 */
export function updateExistingPR(
  results: PatchResult[],
  changes: ValidatedChange[],
  config: Config,
): string {
  const branch = config.prConfig.branch
  const changedCount = results.filter((r) => r.changed).length
  const title = config.prConfig.titleTemplate.replace('{doc_count}', String(changedCount))

  // Switch to branch
  exec(`git checkout ${branch}`)
  exec(`git pull origin ${branch} --rebase`)

  // Stage and commit changes
  const changedDocs = results.filter((r) => r.changed).map((r) => r.doc)
  if (changedDocs.length === 0) {
    throw new Error('No files to commit')
  }

  for (const doc of changedDocs) {
    exec(`git add "${doc}"`)
  }

  const commitMessage = `docs(nightly): update documentation for structural changes

Co-Authored-By: Nightly Docs Agent <noreply@example.com>`

  exec(`git commit -m "${commitMessage}"`)

  // Push
  exec(`git push origin ${branch}`)

  // Update PR title and body
  const prNumber = getOpenPRNumber(branch)
  if (prNumber) {
    const body = generatePRBody(results, changes, config)
    exec(`gh pr edit ${prNumber} --title "${title}" --body "${body.replace(/"/g, '\\"')}"`)
  }

  // Return PR URL
  const prUrl = exec(`gh pr view ${branch} --json url -q .url`)
  return prUrl
}
